### PR TITLE
add support for IPv6 flow labels in nfacctd

### PR DESCRIPTION
**Pull request by ustorbeck**
Hi Paolo, before you add more code for the 3rd aggregation primitives registry I've already moved my local implementation of the IPv6 flow labels to use it. But the implementation is not complete yet. Hints about missing parts are welcome.

### CODE REVIEW

**Review by paololucente — COMMENTED** [review]
Hi Uwe ( @ustorbeck ), Thanks for this contribution! When you say `Hints about missing parts are welcome` you mean that you could not have this tested working correctly yet? I believe that the code to support the 3rd registry is now complete.

**Comment by ustorbeck** [comment]
Hi Paolo, sorry, I was too much focused on the flow label implementation. My comment about missing parts was about the flow label code. It mainly lacks the implementation for pmacctd and the sql plugin and the documentation.
I also think that the support for the 3rd primitives registry is complete now. At least it already works well for me for the flow label reporting with nfacctd and kafka. As I do not know when I have time to add the missing code parts for the flow label implementation, next week is short and quite busy,  I'll submit the commit for the 3rd registry in a separate PR, so that that implementation can be completed in master.

**Comment by paololucente** [comment]
Hi Uwe ( @ustorbeck ), PR #769 was merged. flow label & pmacctd we could leave it for later; whereas docs and SQL part i can contribute since it's not lots of work. If you could release this PR - it is currently marked as a draft - i could merge it an add the two missing parts. Paolo

**Comment by ustorbeck** [comment]
Hi Paolo, thanks for the offer. I will take the opportunity to submit the PR without the flow label implementation for pmacctd. I've cleaned up the PR, have added the missing SQL plugin support and will remove the draft status.

**Pull request merged**
